import {database,failure,sameOrigin} from '@/lib/database';
import {annotationColor} from '@/lib/annotations';
export const runtime='nodejs';
const clean=(value:unknown,max:number)=>typeof value==='string'?value.slice(0,max):'';
const offset=(value:unknown)=>Number.isFinite(Number(value))?Math.max(-1,Math.trunc(Number(value))):-1;

export async function GET(r:Request){try{const articleId=new URL(r.url).searchParams.get('articleId')||'';if(!articleId)return Response.json([]);return Response.json((await database().prepare('SELECT * FROM annotations WHERE articleId=? ORDER BY created ASC').bind(articleId).all()).results);}catch(e){return failure(e);}}
export async function POST(r:Request){try{sameOrigin(r);const b=await r.json() as any;const articleId=clean(b.articleId,120),kind=b.kind==='note'?'note':'highlight';if(!articleId)throw new Error('Choose an article first.');const exists=(await database().prepare('SELECT id FROM articles WHERE id=? LIMIT 1').bind(articleId).all()).results.length;if(!exists)throw new Error('That article no longer exists.');const exactText=kind==='highlight'?clean(b.exactText,12000):'',prefixText=kind==='highlight'?clean(b.prefixText,1000):'',suffixText=kind==='highlight'?clean(b.suffixText,1000):'';if(kind==='highlight'&&!exactText.trim())throw new Error('Select some article text first.');const now=new Date().toISOString(),id=clean(b.id,120)||crypto.randomUUID(),created=clean(b.created,80)||now;const existing=(await database().prepare('SELECT articleId FROM annotations WHERE id=? LIMIT 1').bind(id).all()).results[0];if(existing&&String(existing.articleId)!==articleId)throw new Error('That annotation belongs to a different article.');const row={id,articleId,kind,exactText,prefixText,suffixText,startOffset:kind==='highlight'?offset(b.startOffset):-1,endOffset:kind==='highlight'?offset(b.endOffset):-1,note:clean(b.note,30000),color:annotationColor(b.color),created,updated:now};await database().prepare('INSERT INTO annotations (id,articleId,kind,exactText,prefixText,suffixText,startOffset,endOffset,note,color,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET exactText=excluded.exactText,prefixText=excluded.prefixText,suffixText=excluded.suffixText,startOffset=excluded.startOffset,endOffset=excluded.endOffset,note=excluded.note,color=excluded.color,updated=excluded.updated').bind(...Object.values(row)).run();return Response.json(row);}catch(e){return failure(e);}}
export async function DELETE(r:Request){try{sameOrigin(r);const{id,articleId}=await r.json() as any;if(typeof id!=='string'||!id)throw new Error('Choose an annotation first.');await database().prepare('DELETE FROM annotations WHERE id=? AND articleId=?').bind(id,String(articleId||'')).run();return Response.json({ok:true});}catch(e){return failure(e);}}
