export type Article={id:string;title:string;content:string;transcript:string;url:string;collection:string;tags:string;favorite:number;created:string;headerColor:string};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
function safeHref(raw:string){const value=raw.trim();return /^(https?:\/\/|mailto:|#)/i.test(value)?esc(value):'';}
function inlineMarkdown(source:string){
  const tokens:string[]=[];
  const hold=(value:string)=>`@@MARGIN_INLINE_${tokens.push(value)-1}@@`;
  let text=source.replace(/`([^`\n]+)`/g,(_,code)=>hold(`<code>${esc(code)}</code>`));
  text=text.replace(/\[([^\]\n]+)\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)/g,(_,label,href)=>{const safe=safeHref(href);return safe?hold(`<a href="${safe}" target="_blank" rel="noreferrer">${esc(label)}</a>`):label;});
  text=esc(text);
  text=text.replace(/\*\*([^*\n]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_\n]+)__/g,'<strong>$1</strong>');
  text=text.replace(/~~([^~\n]+)~~/g,'<del>$1</del>');
  text=text.replace(/(^|[^*\w])\*([^*\n]+)\*(?!\*)/g,'$1<em>$2</em>');
  text=text.replace(/(^|[^_\w])_([^_\n]+)_(?!\w)/g,'$1<em>$2</em>');
  return text.replace(/@@MARGIN_INLINE_(\d+)@@/g,(_,index)=>tokens[Number(index)]||'');
}
function splitTableRow(line:string){let value=line.trim();if(value.startsWith('|'))value=value.slice(1);if(value.endsWith('|'))value=value.slice(0,-1);return value.split('|').map(cell=>cell.trim());}
function tableDivider(line:string){const cells=splitTableRow(line);return cells.length>0&&cells.every(cell=>/^:?-{3,}:?$/.test(cell));}
function startsBlock(lines:string[],index:number){const line=lines[index]||'';if(!line.trim())return true;if(/^\s*```/.test(line)||/^\s{0,3}#{1,6}\s+/.test(line)||/^\s{0,3}>/.test(line)||/^\s{0,3}(?:[-+*]|\d+[.)])\s+/.test(line)||/^\s{0,3}(?:-{3,}|\*{3,}|_{3,})\s*$/.test(line))return true;return line.includes('|')&&index+1<lines.length&&tableDivider(lines[index+1]);}
export function html(markdown:string){
  const lines=markdown.replace(/\r\n?/g,'\n').split('\n');
  const out:string[]=[];
  let i=0;
  while(i<lines.length){
    const line=lines[i];
    if(!line.trim()){i++;continue;}
    const fence=line.match(/^\s*```\s*([\w-]+)?\s*$/);
    if(fence){const code:string[]=[];i++;while(i<lines.length&&!/^\s*```\s*$/.test(lines[i]))code.push(lines[i++]);if(i<lines.length)i++;const lang=fence[1]?` class="language-${esc(fence[1])}"`:'';out.push(`<pre><code${lang}>${esc(code.join('\n'))}</code></pre>`);continue;}
    const heading=line.match(/^\s{0,3}(#{1,6})\s+(.+?)\s*#*\s*$/);
    if(heading){const level=heading[1].length;out.push(`<h${level}>${inlineMarkdown(heading[2])}</h${level}>`);i++;continue;}
    if(/^\s{0,3}(?:-{3,}|\*{3,}|_{3,})\s*$/.test(line)){out.push('<hr/>');i++;continue;}
    if(line.includes('|')&&i+1<lines.length&&tableDivider(lines[i+1])){const headers=splitTableRow(line),align=splitTableRow(lines[i+1]);i+=2;const rows:string[][]=[];while(i<lines.length&&lines[i].trim()&&lines[i].includes('|'))rows.push(splitTableRow(lines[i++]));const alignment=(cell:string)=>cell.startsWith(':')&&cell.endsWith(':')?'center':cell.endsWith(':')?'right':cell.startsWith(':')?'left':'';out.push(`<div class="markdown-table-wrap"><table><thead><tr>${headers.map((cell,index)=>`<th${alignment(align[index]||'')?` style="text-align:${alignment(align[index]||'')}"`:''}>${inlineMarkdown(cell)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${headers.map((_,index)=>`<td${alignment(align[index]||'')?` style="text-align:${alignment(align[index]||'')}"`:''}>${inlineMarkdown(row[index]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`);continue;}
    if(/^\s{0,3}>/.test(line)){const quote:string[]=[];while(i<lines.length&&/^\s{0,3}>/.test(lines[i]))quote.push(lines[i++].replace(/^\s{0,3}>\s?/,''));out.push(`<blockquote>${html(quote.join('\n'))}</blockquote>`);continue;}
    const listMatch=line.match(/^\s{0,3}([-+*]|\d+[.)])\s+(.+)$/);
    if(listMatch){const ordered=/\d/.test(listMatch[1]);const tag=ordered?'ol':'ul';const items:string[]=[];while(i<lines.length){const match=lines[i].match(/^\s{0,3}([-+*]|\d+[.)])\s+(.+)$/);if(!match||/\d/.test(match[1])!==ordered)break;let item=match[2];const task=item.match(/^\[([ xX])\]\s+(.*)$/);if(task)item=`<input type="checkbox" disabled${task[1].toLowerCase()==='x'?' checked':''}/> ${inlineMarkdown(task[2])}`;else item=inlineMarkdown(item);items.push(`<li>${item}</li>`);i++;}out.push(`<${tag}>${items.join('')}</${tag}>`);continue;}
    const paragraph:string[]=[line.trim()];i++;while(i<lines.length&&!startsBlock(lines,i)){paragraph.push(lines[i].trim());i++;}out.push(`<p>${inlineMarkdown(paragraph.join(' '))}</p>`);
  }
  return out.join('');
}
export function download(data:Blob,name:string){const url=URL.createObjectURL(data);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function zip(files:[string,string][]){const encoder=new TextEncoder();let offset=0;const parts:Uint8Array[]=[];const central:Uint8Array[]=[];for(const[name,content]of files){const n=encoder.encode(name),b=encoder.encode(content);let crc=0xffffffff;for(const v of b){crc^=v;for(let i=0;i<8;i++)crc=crc&1?(crc>>>1)^0xedb88320:crc>>>1;}crc=(crc^0xffffffff)>>>0;const h=new Uint8Array(30+n.length),d=new DataView(h.buffer);d.setUint32(0,0x04034b50,true);d.setUint16(4,20,true);d.setUint16(6,0x800,true);d.setUint32(14,crc,true);d.setUint32(18,b.length,true);d.setUint32(22,b.length,true);d.setUint16(26,n.length,true);h.set(n,30);parts.push(h,b);const c=new Uint8Array(46+n.length),v=new DataView(c.buffer);v.setUint32(0,0x02014b50,true);v.setUint16(4,20,true);v.setUint16(6,20,true);v.setUint16(8,0x800,true);v.setUint32(16,crc,true);v.setUint32(20,b.length,true);v.setUint32(24,b.length,true);v.setUint16(28,n.length,true);v.setUint32(42,offset,true);c.set(n,46);central.push(c);offset+=h.length+b.length;}const end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,files.length,true);e.setUint16(10,files.length,true);e.setUint32(12,central.reduce((n,c)=>n+c.length,0),true);e.setUint32(16,offset,true);return new Blob([...parts,...central,end] as BlobPart[],{type:'application/epub+zip'});}
export function epub(items:Article[],title:string){const shell=(body:string)=>`<?xml version="1.0" encoding="UTF-8"?><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>${esc(title)}</title><style>body{font-family:serif;line-height:1.65;margin:5%}h1,h2,h3,h4,h5,h6{line-height:1.25}p{margin:1em 0}ul,ol{padding-left:1.6em}blockquote{margin:1.2em 0;padding:.2em 1em;border-left:3px solid #aaa;color:#555}code,pre{font-family:monospace}code{background:#f2f2f2;padding:.1em .25em}pre{overflow:auto;padding:1em;background:#f4f4f4}pre code{padding:0;background:transparent}table{border-collapse:collapse;width:100%;font-family:sans-serif;font-size:.9em}th,td{border:1px solid #ccc;padding:.45em .6em}th{background:#f3f3f3}hr{border:0;border-top:1px solid #ccc;margin:2em 0}a{color:#166b57}</style></head><body>${body}</body></html>`;const files:[string,string][]=[['mimetype','application/epub+zip'],['META-INF/container.xml','<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>'],['OEBPS/nav.xhtml',shell(`<nav epub:type="toc"><h1>${esc(title)}</h1><ol>${items.map((a,i)=>`<li><a href="chapter${i}.xhtml">${esc(a.title)}</a></li>`).join('')}</ol></nav>`)],['OEBPS/content.opf',`<?xml version="1.0"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="book-id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="book-id">urn:uuid:${crypto.randomUUID()}</dc:identifier><dc:title>${esc(title)}</dc:title><dc:language>en</dc:language><dc:creator>Margin</dc:creator><meta property="dcterms:modified">${new Date().toISOString().replace(/\.\d+Z/,'Z')}</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>${items.map((_,i)=>`<item id="c${i}" href="chapter${i}.xhtml" media-type="application/xhtml+xml"/>`).join('')}</manifest><spine>${items.map((_,i)=>`<itemref idref="c${i}"/>`).join('')}</spine></package>`]];items.forEach((a,i)=>files.push([`OEBPS/chapter${i}.xhtml`,shell(`<h1>${esc(a.title)}</h1>${a.url?`<p>Source: ${esc(a.url)}</p>`:''}${html(a.content)}`)]));download(zip(files),title.replace(/[^\p{L}\p{N} -]/gu,'')+'.epub');}
export function pdf(items:Article[],title:string){const w=window.open('','_blank');if(!w)throw new Error('Allow pop-ups to open the PDF print view.');w.document.write(`<!doctype html><html><head><title>${esc(title)}</title><style>@page{size:A4;margin:22mm}body{font:12pt/1.65 Georgia,serif;color:#182923;max-width:760px;margin:30px auto}h1{font-size:28pt;line-height:1.2}h2{font-size:19pt}article+article{break-before:page}p{orphans:3;widows:3}ul,ol{padding-left:1.6em}blockquote{border-left:3px solid #999;padding-left:1em;color:#555}code,pre{font-family:monospace}code{background:#f1f1f1;padding:.1em .25em}pre{padding:1em;background:#f5f5f5;white-space:pre-wrap}pre code{padding:0;background:transparent}table{border-collapse:collapse;width:100%;font:10pt/1.45 Arial,sans-serif}th,td{border:1px solid #ccc;padding:6px 8px}th{background:#f3f3f3}hr{border:0;border-top:1px solid #bbb;margin:2em 0}a{color:#166b57}header{font:11pt Arial;border-bottom:1px solid #ccc;padding:15px 0}button{padding:12px;background:#166b57;color:white;border:0;border-radius:5px;cursor:pointer}@media print{.tools{display:none}}</style></head><body><div class="tools"><button onclick="window.print()">Save as PDF / Print</button><p>Choose “Save as PDF” as your printer or destination.</p></div>${items.map(a=>`<article><header>MARGIN / YOUR READING COLLECTION</header><h1>${esc(a.title)}</h1>${a.url?`<p>Source: ${esc(a.url)}</p>`:''}${html(a.content)}</article>`).join('')}</body></html>`);w.document.close();}
